version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.4
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - mynetwork

  kafka:
    image: quay.io/debezium/kafka:2.4
    ports:
      - 9092:9092
    networks:
      - mynetwork

  mysql:
    image: quay.io/debezium/example-mysql:2.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks:
      - mynetwork

  mysqlterm:
    image: mysql:8.0
    command: sh -c 'exec mysql -h"$$MYSQL_PORT_3306_TCP_ADDR" -P"$$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
    networks:
      - mynetwork

  connect:
    image: quay.io/debezium/connect:2.4
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - mynetwork

  watcher:
    image: quay.io/debezium/kafka:2.4
    command: watch-topic -a -k dbserver1.inventory.customers
    networks:
      - mynetwork

networks:
  mynetwork:
